<a href="https://colab.research.google.com/github/Rohitv97/Data-Science-Lab/blob/master/Lab1/Lab1_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt

**Question 1**
Create a (4 x 2) integer array and print it's attributes

In [6]:
array = np.random.rand(4,2)
print(array)

# Print attributes of Array
print('Type of Array:', type(array))
print('Type of Elements in array: ', array.dtype)
print('Dimension of array: ', array.ndim)
print('Shape of array: ', array.shape)
print('No. of items in array: ', array.itemsize)

[[0.79972817 0.53029759]
 [0.38190914 0.3587613 ]
 [0.18629404 0.22545779]
 [0.51543401 0.63846068]]
Type of Array: <class 'numpy.ndarray'>
Type of Elements in array:  float64
Dimension of array:  2
Shape of array:  (4, 2)
No. of items in array:  8


**Question 2**
Create an array of dimension (1,10) and sort it in ascending and descending order

In [40]:
array = np.random.rand(1,10)
print('Original Array: ', array)

sorted_array = np.sort(array)
print('Ascending Order Sorted: ', sorted_array)

# sorted_array = np.fliplr(sorted_array) This also works. Flips the array
sorted_array = np.sort(array, axis=0)
print('Descending Order Sorted: ', sorted_array)

Original Array:  [[0.63962592 0.77430346 0.31348251 0.47636898 0.88149602 0.82980846
  0.35685475 0.73619277 0.56204664 0.05414632]]
Ascending Order Sorted:  [[0.05414632 0.31348251 0.35685475 0.47636898 0.56204664 0.63962592
  0.73619277 0.77430346 0.82980846 0.88149602]]
Descending Order Sorted:  [[0.63962592 0.77430346 0.31348251 0.47636898 0.88149602 0.82980846
  0.35685475 0.73619277 0.56204664 0.05414632]]


**Question 3**
Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [15]:
array = np.array([1,2,3,4,5,6,7,8,9])
new_array = np.reshape(array, (3,3))
print('New Reshaped Array: ', new_array)

New Reshaped Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


**Question 4**
Stack two arrays of any size horizontally and vertically

In [22]:
a = np.random.randint(0,10, (2,3))
b = np.random.randint(0,20, (2,3))

print(a)
print(b)

print('\n Stacking Horizontally')
print(np.stack((a,b)))

print('\n Stacking Vertically')
print(np.stack((a,b), axis=-1))

[[1 9 6]
 [4 6 8]]
[[19  0  6]
 [ 7 16  2]]

 Stacking Horizontally
[[[ 1  9  6]
  [ 4  6  8]]

 [[19  0  6]
  [ 7 16  2]]]

 Stacking Vertically
[[[ 1 19]
  [ 9  0]
  [ 6  6]]

 [[ 4  7]
  [ 6 16]
  [ 8  2]]]


**Question 5**
Create two array of same size and find commom elements

In [23]:
a = np.random.randint(0,10, (2,3))
b = np.random.randint(0,20, (2,3))

print(a)
print(b)

print('\n')

print('Common Elements: ', np.intersect1d(a,b))

[[7 3 7]
 [5 5 9]]
[[ 2  9  3]
 [ 5 11  3]]


Common Elements:  [3 5 9]


**Question 6**
Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [26]:
a = np.random.randint(0,10, (5,5))
print(a)

print('\nRow: \n')
for row in a:
  print('Minimum: ', np.amin(row))
  print('Maximum: ', np.amax(row))
print('\nColumn: \n')
for column in a.T:
  print('Minimum: ', np.amin(column))
  print('Maximum: ', np.amax(column))

[[2 7 7 9 7]
 [1 6 7 5 1]
 [1 5 9 7 3]
 [0 3 3 0 2]
 [2 1 8 7 0]]

Row: 

Minimum:  2
Maximum:  9
Minimum:  1
Maximum:  7
Minimum:  1
Maximum:  9
Minimum:  0
Maximum:  3
Minimum:  0
Maximum:  8

Column: 

Minimum:  0
Maximum:  2
Minimum:  1
Maximum:  7
Minimum:  3
Maximum:  9
Minimum:  0
Maximum:  9
Minimum:  0
Maximum:  7


**Question 7**
Create an array of size 100 and compute the mean, median, standard deviation.

In [28]:
a = np.random.rand(100)
print('Mean of Array: ', np.mean(a))
print('Median of Array: ', np.median(a))
print('Standard Deviation of Array: ', np.std(a))

Mean of Array:  0.5329084097530418
Median of Array:  0.5227862681810431
Standard Deviation of Array:  0.269232919050339


**Quesiton 8**
Normalize a 5x5 random matrix

In [42]:
a = np.random.rand(5,5)
print(a)

min_a = np.amin(a)
max_a = np.amax(a)

for i in range(len(a)):
  for j in range(len(a[i])):
    val = a[i][j]
    val = (val - min_a)/(max_a - min_a)
    a[i][j] = val

print('Normalized Array:\n')
print(a)

[[0.73542421 0.57016564 0.2495726  0.21354448 0.74577106]
 [0.46392751 0.94813971 0.99652507 0.20397074 0.93027145]
 [0.659007   0.1496008  0.92521505 0.86053333 0.12962021]
 [0.49546116 0.13580834 0.29990007 0.81757121 0.32104462]
 [0.27082619 0.63676159 0.41698384 0.06314139 0.99384525]]
Normalized Array:

[[0.72026417 0.54321096 0.19973695 0.16113747 0.73134948]
 [0.42939054 0.94816134 1.         0.15088045 0.92901781]
 [0.638393   0.09263008 0.92360053 0.85430243 0.07122346]
 [0.46317476 0.07785324 0.25365633 0.80827406 0.27630999]
 [0.22250742 0.61455992 0.37909646 0.         0.99712892]]


**Question 9**
Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [61]:
A = np.random.rand(4,4,3)
B = np.random.rand(4,4)

A_new = A.reshape(12, 4)
print(A_new,'\n')
print(B, '\n')

product = np.dot(A_new, B)
print('Resulting Matrix:')
print(product)

[[0.87217307 0.8978849  0.86703178 0.67057461]
 [0.43114287 0.49420674 0.30451088 0.84690292]
 [0.73952648 0.12846643 0.93293847 0.56185238]
 [0.25839215 0.7946635  0.17562826 0.34346691]
 [0.92597037 0.73968177 0.63185036 0.94548466]
 [0.5831142  0.40583879 0.95113522 0.99539758]
 [0.41905525 0.90060075 0.27265956 0.64547796]
 [0.973911   0.50565187 0.78514456 0.56631862]
 [0.29210609 0.38778436 0.66035146 0.34813905]
 [0.5561574  0.81852735 0.70040665 0.98513462]
 [0.87477483 0.93385898 0.78123746 0.69892962]
 [0.50091615 0.62666045 0.39935118 0.55351019]] 

[[0.65368188 0.71722732 0.17086073 0.86874353]
 [0.10019479 0.06276388 0.80616538 0.83545138]
 [0.47918742 0.08187375 0.20712285 0.43554756]
 [0.92721639 0.208354   0.01438398 0.08229345]] 

Resulting Matrix:
[[1.69732562 0.89260514 1.06209147 1.94065135]
 [1.26252728 0.54163283 0.54733075 0.98976181]
 [1.46429784 0.73191901 0.43123577 1.20236213]
 [0.6511544  0.32114412 0.72609632 0.99313875]
 [1.85884593 0.95928401 0.89898829 1